/**
 * Cloudflare Worker Entry Point for SAAR Business Support Solution.
 * Serves static assets generated by Astro and routes serverless API requests.
 */

import { handleEnquiryRequest } from './lib/server/enquiry-handler';
import type { EnquiryServerEnv } from './types/enquiry';

export interface Env extends EnquiryServerEnv {
  ASSETS?: {
    fetch: (request: Request | string) => Promise<Response>;
  };
}

export default {
  async fetch(request: Request, env: Env, _ctx?: unknown): Promise<Response> {
    const url = new URL(request.url);

    // Route: /api/enquiry
    if (url.pathname === '/api/enquiry') {
      if (request.method === 'POST') {
        return handleEnquiryRequest(request, env);
      }
      if (request.method === 'OPTIONS') {
        return new Response(null, {
          status: 204,
          headers: {
            Allow: 'POST, OPTIONS',
            'Access-Control-Allow-Methods': 'POST, OPTIONS',
            'Access-Control-Allow-Headers': 'Content-Type',
          },
        });
      }
      return new Response(
        JSON.stringify({ success: false, error: 'Method Not Allowed' }),
        {
          status: 405,
          headers: {
            'Content-Type': 'application/json; charset=utf-8',
            Allow: 'POST, OPTIONS',
          },
        }
      );
    }

    // Delegate static asset serving to the ASSETS binding
    if (env.ASSETS) {
      return env.ASSETS.fetch(request);
    }

    return new Response('Not Found', { status: 404 });
  },
};
